// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function assertEquals(actual, expected, msg) {
  Buntest.expect(actual, msg !== undefined ? Primitive_option.valFromOption(msg) : undefined).toEqual(expected);
}

function assertExists(actual, msg) {
  Buntest.expect(actual, msg !== undefined ? Primitive_option.valFromOption(msg) : undefined).toBeDefined();
  Buntest.expect(actual, msg !== undefined ? Primitive_option.valFromOption(msg) : undefined).not.toBeNull();
}

function assertStringIncludes(actual, expected, msg) {
  Buntest.expect(actual, msg !== undefined ? Primitive_option.valFromOption(msg) : undefined).toContain(expected);
}

function assertArrayIncludes(actual, expected, msg) {
  Buntest.expect(actual, msg !== undefined ? Primitive_option.valFromOption(msg) : undefined).toEqual(Buntest.expect.arrayContaining(expected));
}

export {
  assertEquals,
  assertExists,
  assertStringIncludes,
  assertArrayIncludes,
}
/* bun:test Not a pure module */
