// Generated by ReScript, PLEASE EDIT WITH CARE


function splitLines(text) {
  return text.split("\n").map(line => line.trim()).filter(line => line !== "");
}

function splitRow(line) {
  return line.split(",").map(prim => prim.trim());
}

function parse(text, options) {
  let rows = splitLines(text).map(splitRow);
  if (options.skipFirstRow) {
    return rows.slice(1);
  } else {
    return rows;
  }
}

function parseAsRecords(text, _options) {
  let rows = splitLines(text).map(splitRow);
  let len = rows.length;
  if (len === 1) {
    return [];
  }
  if (len === 0) {
    return [];
  }
  let headers = rows[0];
  return rows.slice(1).map(row => {
    let dict = {};
    headers.forEach((header, i) => {
      let value = row[i];
      if (value !== undefined) {
        dict[header] = value;
        return;
      }
    });
    return dict;
  });
}

export {
  splitLines,
  splitRow,
  parse,
  parseAsRecords,
}
/* No side effect */
