// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Assert from "@std/assert";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Bdd from "@std/testing/bdd";

Bdd.describe("Project Configuration", () => {
  Bdd.describe("rescript.json", () => {
    Bdd.it("should have valid JSON structure", async () => {
      let content = await Deno.readTextFile("rescript.json");
      let config = JSON.parse(content);
      Assert.assertExists(config.name, "Should have name field");
    });
    Bdd.it("should have correct project name", async () => {
      let content = await Deno.readTextFile("rescript.json");
      let config = JSON.parse(content);
      Assert.assertEquals(config.name, "supernorma", "Project name should be supernorma");
    });
    Bdd.it("should use ES module output", async () => {
      let content = await Deno.readTextFile("rescript.json");
      let config = JSON.parse(content);
      let specs = config["package-specs"];
      let first = Stdlib_Option.getOrThrow(specs[0], "package-specs should have one entry");
      Assert.assertEquals(first.module, "esmodule", "Should output ES modules");
    });
    Bdd.it("should use .res.js suffix", async () => {
      let content = await Deno.readTextFile("rescript.json");
      let config = JSON.parse(content);
      Assert.assertEquals(config.suffix, ".res.js", "Should use .res.js suffix");
    });
    Bdd.it("should not use legacy bs-dependencies", async () => {
      let content = await Deno.readTextFile("rescript.json");
      let config = JSON.parse(content);
      Assert.assertEquals(config["bs-dependencies"], undefined, "Should not have bs-dependencies");
    });
  });
  Bdd.describe("deno.json", () => {
    Bdd.it("should have valid JSON structure", async () => {
      let content = await Deno.readTextFile("deno.json");
      let config = JSON.parse(content);
      Assert.assertExists(config.name, "Should have name field");
    });
    Bdd.it("should have correct project name and version", async () => {
      let content = await Deno.readTextFile("deno.json");
      let config = JSON.parse(content);
      Assert.assertEquals(config.name, "@hyperpolymath/supernorma", "Project name should be @hyperpolymath/supernorma");
      Assert.assertExists(config.version, "Should have version");
    });
    Bdd.it("should have ReScript build tasks", async () => {
      let content = await Deno.readTextFile("deno.json");
      let config = JSON.parse(content);
      let tasks = config.tasks;
      Assert.assertExists(tasks["rescript:build"], "Should have rescript:build task");
      Assert.assertExists(tasks["rescript:clean"], "Should have rescript:clean task");
    });
    Bdd.it("should have test task", async () => {
      let content = await Deno.readTextFile("deno.json");
      let config = JSON.parse(content);
      let tasks = config.tasks;
      Assert.assertExists(tasks.test, "Should have test task");
    });
    Bdd.it("should have import map", async () => {
      let content = await Deno.readTextFile("deno.json");
      let config = JSON.parse(content);
      let imports = config.imports;
      Assert.assertExists(imports, "Should have imports");
      Assert.assertExists(imports["@std/assert"], "Should import @std/assert");
    });
  });
  Bdd.describe("guix.scm", () => {
    Bdd.it("should exist and define supernorma package", async () => {
      let content = await Deno.readTextFile("guix.scm");
      Assert.assertStringIncludes(content, "SuperNorma", "Should define SuperNorma");
      Assert.assertStringIncludes(content, "define-public", "Should have package definition");
    });
    Bdd.it("should have SPDX license header", async () => {
      let content = await Deno.readTextFile("guix.scm");
      Assert.assertStringIncludes(content, "SPDX-License-Identifier", "Should have SPDX header");
    });
  });
});

Bdd.describe("RSR Compliance Files", () => {
  Bdd.it("should have STATE.a2ml", async () => {
    let content = await Deno.readTextFile(".machine_readable/6a2/STATE.a2ml");
    Assert.assertStringIncludes(content, "supernorma", "Should reference project");
  });
  Bdd.it("should have META.a2ml", async () => {
    let content = await Deno.readTextFile(".machine_readable/6a2/META.a2ml");
    Assert.assertStringIncludes(content, "supernorma", "Should reference project");
  });
  Bdd.it("should have ECOSYSTEM.a2ml", async () => {
    let content = await Deno.readTextFile(".machine_readable/6a2/ECOSYSTEM.a2ml");
    Assert.assertStringIncludes(content, "supernorma", "Should reference project");
  });
  Bdd.it("should have RSR_COMPLIANCE.adoc", async () => {
    let content = await Deno.readTextFile("RSR_COMPLIANCE.adoc");
    Assert.assertExists(content, "Should be able to read RSR_COMPLIANCE.adoc");
  });
  Bdd.it("should have SECURITY.md", async () => {
    let content = await Deno.readTextFile("SECURITY.md");
    Assert.assertExists(content, "Should be able to read SECURITY.md");
  });
  Bdd.it("should have LICENSE", async () => {
    let content = await Deno.readTextFile("LICENSE");
    Assert.assertExists(content, "Should be able to read LICENSE");
  });
});

/*  Not a pure module */
