// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Assert from "../../src/bindings/Assert.res.js";
import * as Runtime from "../../src/bindings/Runtime.res.js";
import * as Buntest from "bun:test";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

Buntest.describe("Project Configuration", () => {
  Buntest.describe("rescript.json", () => {
    Buntest.it("should have valid JSON structure", async () => {
      let content = await Runtime.readTextFile("rescript.json");
      let config = JSON.parse(content);
      return Assert.assertExists(config.name, "Should have name field");
    });
    Buntest.it("should have correct project name", async () => {
      let content = await Runtime.readTextFile("rescript.json");
      let config = JSON.parse(content);
      return Assert.assertEquals(config.name, "@hyperpolymath/supernorma", "Project name should be @hyperpolymath/supernorma");
    });
    Buntest.it("should use ES module output", async () => {
      let content = await Runtime.readTextFile("rescript.json");
      let config = JSON.parse(content);
      let specs = config["package-specs"];
      let first = Stdlib_Option.getOrThrow(specs[0], "package-specs should have one entry");
      return Assert.assertEquals(first.module, "esmodule", "Should output ES modules");
    });
    Buntest.it("should use .res.js suffix", async () => {
      let content = await Runtime.readTextFile("rescript.json");
      let config = JSON.parse(content);
      return Assert.assertEquals(config.suffix, ".res.js", "Should use .res.js suffix");
    });
    Buntest.it("should not use legacy bs-dependencies", async () => {
      let content = await Runtime.readTextFile("rescript.json");
      let config = JSON.parse(content);
      return Assert.assertEquals(config["bs-dependencies"], undefined, "Should not have bs-dependencies");
    });
  });
  Buntest.describe("package.json", () => {
    Buntest.it("should have valid JSON structure", async () => {
      let content = await Runtime.readTextFile("package.json");
      let config = JSON.parse(content);
      return Assert.assertExists(config.name, "Should have name field");
    });
    Buntest.it("should have correct project name and version", async () => {
      let content = await Runtime.readTextFile("package.json");
      let config = JSON.parse(content);
      Assert.assertEquals(config.name, "@hyperpolymath/supernorma", "Project name should be @hyperpolymath/supernorma");
      return Assert.assertExists(config.version, "Should have version");
    });
    Buntest.it("should have ReScript build scripts", async () => {
      let content = await Runtime.readTextFile("package.json");
      let config = JSON.parse(content);
      let scripts = config.scripts;
      Assert.assertExists(scripts["rescript:build"], "Should have rescript:build script");
      return Assert.assertExists(scripts["rescript:clean"], "Should have rescript:clean script");
    });
    Buntest.it("should have test script", async () => {
      let content = await Runtime.readTextFile("package.json");
      let config = JSON.parse(content);
      let scripts = config.scripts;
      return Assert.assertExists(scripts.test, "Should have test script");
    });
    Buntest.it("should declare the rescript devDependency", async () => {
      let content = await Runtime.readTextFile("package.json");
      let config = JSON.parse(content);
      let devDeps = config.devDependencies;
      Assert.assertExists(devDeps, "Should have devDependencies");
      return Assert.assertExists(devDeps.rescript, "Should depend on rescript");
    });
  });
  Buntest.describe("guix.scm", () => {
    Buntest.it("should exist and define supernorma package", async () => {
      let content = await Runtime.readTextFile("guix.scm");
      Assert.assertStringIncludes(content, "SuperNorma", "Should define SuperNorma");
      return Assert.assertStringIncludes(content, "define-public", "Should have package definition");
    });
    Buntest.it("should have SPDX license header", async () => {
      let content = await Runtime.readTextFile("guix.scm");
      return Assert.assertStringIncludes(content, "SPDX-License-Identifier", "Should have SPDX header");
    });
  });
});

Buntest.describe("RSR Compliance Files", () => {
  Buntest.it("should have STATE.a2ml", async () => {
    let content = await Runtime.readTextFile(".machine_readable/6a2/STATE.a2ml");
    return Assert.assertStringIncludes(content, "supernorma", "Should reference project");
  });
  Buntest.it("should have META.a2ml", async () => {
    let content = await Runtime.readTextFile(".machine_readable/6a2/META.a2ml");
    return Assert.assertStringIncludes(content, "supernorma", "Should reference project");
  });
  Buntest.it("should have ECOSYSTEM.a2ml", async () => {
    let content = await Runtime.readTextFile(".machine_readable/6a2/ECOSYSTEM.a2ml");
    return Assert.assertStringIncludes(content, "supernorma", "Should reference project");
  });
  Buntest.it("should have RSR_COMPLIANCE.adoc", async () => {
    let content = await Runtime.readTextFile("RSR_COMPLIANCE.adoc");
    return Assert.assertExists(content, "Should be able to read RSR_COMPLIANCE.adoc");
  });
  Buntest.it("should have SECURITY.md", async () => {
    let content = await Runtime.readTextFile("SECURITY.md");
    return Assert.assertExists(content, "Should be able to read SECURITY.md");
  });
  Buntest.it("should have LICENSE", async () => {
    let content = await Runtime.readTextFile("LICENSE");
    return Assert.assertExists(content, "Should be able to read LICENSE");
  });
});

/*  Not a pure module */
