// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Assert from "../../src/bindings/Assert.res.js";
import * as Runtime from "../../src/bindings/Runtime.res.js";
import * as Buntest from "bun:test";
import * as Promises from "node:fs/promises";

Buntest.describe("HTML Form Integration", () => {
  Buntest.describe("ui/webform.html", () => {
    Buntest.it("should be valid HTML document", async () => {
      let content = await Runtime.readTextFile("ui/webform.html");
      Assert.assertStringIncludes(content, "<!DOCTYPE html>", "Should have DOCTYPE");
      Assert.assertStringIncludes(content, "<html>", "Should have html tag");
      return Assert.assertStringIncludes(content, "</html>", "Should close html tag");
    });
    Buntest.it("should contain a form element", async () => {
      let content = await Runtime.readTextFile("ui/webform.html");
      Assert.assertStringIncludes(content, "<form>", "Should have form tag");
      return Assert.assertStringIncludes(content, "</form>", "Should close form tag");
    });
    Buntest.it("should have income input field", async () => {
      let content = await Runtime.readTextFile("ui/webform.html");
      Assert.assertStringIncludes(content, "Income", "Should have Income label");
      return Assert.assertStringIncludes(content, "type='number'", "Should have number input");
    });
    Buntest.it("should have expenses input field", async () => {
      let content = await Runtime.readTextFile("ui/webform.html");
      return Assert.assertStringIncludes(content, "Expenses", "Should have Expenses label");
    });
    Buntest.it("should have submit button", async () => {
      let content = await Runtime.readTextFile("ui/webform.html");
      return Assert.assertStringIncludes(content, "type='submit'", "Should have submit button");
    });
    Buntest.it("should have SuperNorma branding", async () => {
      let content = await Runtime.readTextFile("ui/webform.html");
      return Assert.assertStringIncludes(content, "SuperNorma", "Should reference SuperNorma");
    });
  });
  Buntest.describe("ui/style.css", () => {
    Buntest.it("should exist and be readable", async () => {
      let content = await Runtime.readTextFile("ui/style.css");
      return Assert.assertExists(content, "Should be able to read style.css");
    });
  });
});

Buntest.describe("Project Structure", () => {
  Buntest.it("should have ReScript source files", async () => {
    let srcDir = await Promises.readdir("src");
    let resFiles = srcDir.filter(name => name.endsWith(".res"));
    return Assert.assertEquals(resFiles.length >= 1, true, "Should have at least one .res file");
  });
  Buntest.it("should have compiled JavaScript files", async () => {
    let srcDir = await Promises.readdir("src");
    let jsFiles = srcDir.filter(name => name.endsWith(".res.js"));
    return Assert.assertEquals(jsFiles.length >= 1, true, "Should have at least one .res.js file");
  });
  Buntest.it("should have matching .res and .res.js files", async () => {
    let srcDir = await Promises.readdir("src");
    let resFiles = srcDir.filter(name => name.endsWith(".res"));
    let jsFiles = srcDir.filter(name => name.endsWith(".res.js"));
    resFiles.forEach(resFile => {
      let baseName = resFile.replace(".res", "");
      let hasCompiled = jsFiles.some(js => js === baseName + `.res.js`);
      Assert.assertEquals(hasCompiled, true, resFile + ` should have compiled .res.js file`);
    });
  });
});

/*  Not a pure module */
