// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Assert from "@std/assert";
import * as Bdd from "@std/testing/bdd";

Bdd.describe("HTML Form Integration", () => {
  Bdd.describe("ui/webform.html", () => {
    Bdd.it("should be valid HTML document", async () => {
      let content = await Deno.readTextFile("ui/webform.html");
      Assert.assertStringIncludes(content, "<!DOCTYPE html>", "Should have DOCTYPE");
      Assert.assertStringIncludes(content, "<html>", "Should have html tag");
      Assert.assertStringIncludes(content, "</html>", "Should close html tag");
    });
    Bdd.it("should contain a form element", async () => {
      let content = await Deno.readTextFile("ui/webform.html");
      Assert.assertStringIncludes(content, "<form>", "Should have form tag");
      Assert.assertStringIncludes(content, "</form>", "Should close form tag");
    });
    Bdd.it("should have income input field", async () => {
      let content = await Deno.readTextFile("ui/webform.html");
      Assert.assertStringIncludes(content, "Income", "Should have Income label");
      Assert.assertStringIncludes(content, "type='number'", "Should have number input");
    });
    Bdd.it("should have expenses input field", async () => {
      let content = await Deno.readTextFile("ui/webform.html");
      Assert.assertStringIncludes(content, "Expenses", "Should have Expenses label");
    });
    Bdd.it("should have submit button", async () => {
      let content = await Deno.readTextFile("ui/webform.html");
      Assert.assertStringIncludes(content, "type='submit'", "Should have submit button");
    });
    Bdd.it("should have SuperNorma branding", async () => {
      let content = await Deno.readTextFile("ui/webform.html");
      Assert.assertStringIncludes(content, "SuperNorma", "Should reference SuperNorma");
    });
  });
  Bdd.describe("ui/style.css", () => {
    Bdd.it("should exist and be readable", async () => {
      let content = await Deno.readTextFile("ui/style.css");
      Assert.assertExists(content, "Should be able to read style.css");
    });
  });
});

Bdd.describe("Project Structure", () => {
  Bdd.it("should have ReScript source files", async () => {
    let srcDir = await Array.fromAsync(Deno.readDir("src"));
    let resFiles = srcDir.filter(entry => entry.name.endsWith(".res"));
    Assert.assertEquals(resFiles.length >= 1, true, "Should have at least one .res file");
  });
  Bdd.it("should have compiled JavaScript files", async () => {
    let srcDir = await Array.fromAsync(Deno.readDir("src"));
    let jsFiles = srcDir.filter(entry => entry.name.endsWith(".res.js"));
    Assert.assertEquals(jsFiles.length >= 1, true, "Should have at least one .res.js file");
  });
  Bdd.it("should have matching .res and .res.js files", async () => {
    let srcDir = await Array.fromAsync(Deno.readDir("src"));
    let resFiles = srcDir.filter(entry => entry.name.endsWith(".res"));
    let jsFiles = srcDir.filter(entry => entry.name.endsWith(".res.js"));
    resFiles.forEach(resFile => {
      let baseName = resFile.name.replace(".res", "");
      let hasCompiled = jsFiles.some(js => js.name === baseName + `.res.js`);
      Assert.assertEquals(hasCompiled, true, resFile.name + ` should have compiled .res.js file`);
    });
  });
});

/*  Not a pure module */
