// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

function calculateNetIncome(record) {
  return record.income - record.expenses;
}

function isSurplus(record) {
  return record.income > record.expenses;
}

function calculatePensionProjection(pension, currentAge, annualGrowthRateOpt) {
  let annualGrowthRate = annualGrowthRateOpt !== undefined ? annualGrowthRateOpt : 0.05;
  let yearsToRetirement = pension.drawdownAge - currentAge | 0;
  if (yearsToRetirement <= 0) {
    return pension.amount;
  }
  let futureValue = pension.amount * Math.pow(1.0 + annualGrowthRate, yearsToRetirement);
  return Math.round(futureValue * 100.0) / 100.0;
}

function calculateTotalSavings(records) {
  return Stdlib_Array.reduce(records, 0.0, (total, record) => total + record.savings);
}

let version = "0.1.0";

let projectName = "SuperNorma";

export {
  version,
  projectName,
  calculateNetIncome,
  isSurplus,
  calculatePensionProjection,
  calculateTotalSavings,
}
/* No side effect */
