// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Csv from "../../src/bindings/Csv.res.js";
import * as Assert from "../../src/bindings/Assert.res.js";
import * as Runtime from "../../src/bindings/Runtime.res.js";
import * as Buntest from "bun:test";
import * as Stdlib_Float from "@rescript/runtime/lib/es6/Stdlib_Float.js";

Buntest.describe("Data Files", () => {
  Buntest.describe("workbook/template.csv", () => {
    Buntest.it("should have valid CSV structure", async () => {
      let content = await Runtime.readTextFile("workbook/template.csv");
      let records = Csv.parse(content, {
        skipFirstRow: false
      });
      return Assert.assertEquals(records.length >= 2, true, "Should have at least 2 rows (header + data)");
    });
    Buntest.it("should contain required columns", async () => {
      let content = await Runtime.readTextFile("workbook/template.csv");
      let records = Csv.parse(content, {
        skipFirstRow: false
      });
      let headers = records[0];
      if (headers !== undefined) {
        Assert.assertArrayIncludes(headers, ["Income"], "Should have Income column");
        Assert.assertArrayIncludes(headers, ["Expenses"], "Should have Expenses column");
        return Assert.assertArrayIncludes(headers, ["Savings"], "Should have Savings column");
      } else {
        return Assert.assertExists(undefined, "Headers should exist");
      }
    });
    Buntest.it("should have valid numeric values", async () => {
      let content = await Runtime.readTextFile("workbook/template.csv");
      let records = Csv.parseAsRecords(content, {
        skipFirstRow: true
      });
      records.forEach(row => {
        let values = Object.values(row);
        values.forEach(value => {
          let num = Stdlib_Float.fromString(value);
          Assert.assertExists(num, `Value '` + value + `' should be a valid number`);
        });
      });
    });
  });
  Buntest.describe("workbook/pensions_model.csv", () => {
    Buntest.it("should have valid pension model structure", async () => {
      let content = await Runtime.readTextFile("workbook/pensions_model.csv");
      let records = Csv.parse(content, {
        skipFirstRow: false
      });
      Assert.assertEquals(records.length >= 2, true, "Should have at least 2 rows");
      let headers = records[0];
      if (headers !== undefined) {
        Assert.assertArrayIncludes(headers, ["Type"], "Should have Type column");
        return Assert.assertArrayIncludes(headers, ["Amount"], "Should have Amount column");
      } else {
        return Assert.assertExists(undefined, "Headers should exist");
      }
    });
    Buntest.it("should have valid pension types", async () => {
      let content = await Runtime.readTextFile("workbook/pensions_model.csv");
      let records = Csv.parseAsRecords(content, {
        skipFirstRow: true
      });
      let validTypes = [
        "DB",
        "DC",
        "SIPP",
        "ISA",
        "State"
      ];
      records.forEach(row => {
        let pensionType = row["Type"];
        if (pensionType !== undefined) {
          return Assert.assertArrayIncludes(validTypes, [pensionType], `Pension type '` + pensionType + `' should be valid`);
        } else {
          return Assert.assertExists(undefined, "Type column should exist");
        }
      });
    });
  });
  Buntest.describe("data/sample_input/income_example.csv", () => {
    Buntest.it("should have valid income data", async () => {
      let content = await Runtime.readTextFile("data/sample_input/income_example.csv");
      let records = Csv.parse(content, {
        skipFirstRow: false
      });
      Assert.assertEquals(records.length >= 2, true, "Should have at least 2 rows");
      let headers = records[0];
      if (headers !== undefined) {
        Assert.assertArrayIncludes(headers, ["Income Source"], "Should have Income Source column");
        return Assert.assertArrayIncludes(headers, ["Amount"], "Should have Amount column");
      } else {
        return Assert.assertExists(undefined, "Headers should exist");
      }
    });
  });
});

/*  Not a pure module */
