// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Csv from "@std/csv";
import * as Assert from "@std/assert";
import * as Stdlib_Float from "@rescript/runtime/lib/es6/Stdlib_Float.js";
import * as Bdd from "@std/testing/bdd";

Bdd.describe("Data Files", () => {
  Bdd.describe("workbook/template.csv", () => {
    Bdd.it("should have valid CSV structure", async () => {
      let content = await Deno.readTextFile("workbook/template.csv");
      let records = Csv.parse(content, {
        skipFirstRow: false
      });
      Assert.assertEquals(records.length >= 2, true, "Should have at least 2 rows (header + data)");
    });
    Bdd.it("should contain required columns", async () => {
      let content = await Deno.readTextFile("workbook/template.csv");
      let records = Csv.parse(content, {
        skipFirstRow: false
      });
      let headers = records[0];
      if (headers !== undefined) {
        Assert.assertArrayIncludes(headers, ["Income"], "Should have Income column");
        Assert.assertArrayIncludes(headers, ["Expenses"], "Should have Expenses column");
        Assert.assertArrayIncludes(headers, ["Savings"], "Should have Savings column");
      } else {
        Assert.assertExists(undefined, "Headers should exist");
      }
    });
    Bdd.it("should have valid numeric values", async () => {
      let content = await Deno.readTextFile("workbook/template.csv");
      let records = Csv.parse(content, {
        skipFirstRow: true
      });
      records.forEach(row => {
        let values = Object.values(row);
        values.forEach(value => {
          let num = Stdlib_Float.fromString(value);
          Assert.assertExists(num, `Value '` + value + `' should be a valid number`);
        });
      });
    });
  });
  Bdd.describe("workbook/pensions_model.csv", () => {
    Bdd.it("should have valid pension model structure", async () => {
      let content = await Deno.readTextFile("workbook/pensions_model.csv");
      let records = Csv.parse(content, {
        skipFirstRow: false
      });
      Assert.assertEquals(records.length >= 2, true, "Should have at least 2 rows");
      let headers = records[0];
      if (headers !== undefined) {
        Assert.assertArrayIncludes(headers, ["Type"], "Should have Type column");
        Assert.assertArrayIncludes(headers, ["Amount"], "Should have Amount column");
      } else {
        Assert.assertExists(undefined, "Headers should exist");
      }
    });
    Bdd.it("should have valid pension types", async () => {
      let content = await Deno.readTextFile("workbook/pensions_model.csv");
      let records = Csv.parse(content, {
        skipFirstRow: true
      });
      let validTypes = [
        "DB",
        "DC",
        "SIPP",
        "ISA",
        "State"
      ];
      records.forEach(row => {
        let pensionType = row["Type"];
        if (pensionType !== undefined) {
          Assert.assertArrayIncludes(validTypes, [pensionType], `Pension type '` + pensionType + `' should be valid`);
        } else {
          Assert.assertExists(undefined, "Type column should exist");
        }
      });
    });
  });
  Bdd.describe("data/sample_input/income_example.csv", () => {
    Bdd.it("should have valid income data", async () => {
      let content = await Deno.readTextFile("data/sample_input/income_example.csv");
      let records = Csv.parse(content, {
        skipFirstRow: false
      });
      Assert.assertEquals(records.length >= 2, true, "Should have at least 2 rows");
      let headers = records[0];
      if (headers !== undefined) {
        Assert.assertArrayIncludes(headers, ["Income Source"], "Should have Income Source column");
        Assert.assertArrayIncludes(headers, ["Amount"], "Should have Amount column");
      } else {
        Assert.assertExists(undefined, "Headers should exist");
      }
    });
  });
});

/*  Not a pure module */
