// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Assert from "@std/assert";
import * as Bdd from "@std/testing/bdd";

function countChar(str, char) {
  let parts = str.split(char);
  return parts.length - 1 | 0;
}

Bdd.describe("DAX Expressions", () => {
  Bdd.describe("measures.dax", () => {
    Bdd.it("should contain TotalSavings measure", async () => {
      let content = await Deno.readTextFile("dax/measures.dax");
      Assert.assertStringIncludes(content, "TotalSavings", "Should define TotalSavings measure");
      Assert.assertStringIncludes(content, "SUM", "Should use SUM function");
    });
    Bdd.it("should contain NetIncome measure", async () => {
      let content = await Deno.readTextFile("dax/measures.dax");
      Assert.assertStringIncludes(content, "NetIncome", "Should define NetIncome measure");
      Assert.assertStringIncludes(content, "SUM", "Should use SUM function for Income");
      Assert.assertStringIncludes(content, "Expenses", "Should reference Expenses");
    });
    Bdd.it("should reference Finance table", async () => {
      let content = await Deno.readTextFile("dax/measures.dax");
      Assert.assertStringIncludes(content, "'Finance'", "Should reference Finance table");
    });
  });
  Bdd.describe("columns.dax", () => {
    Bdd.it("should contain IsSurplus column", async () => {
      let content = await Deno.readTextFile("dax/columns.dax");
      Assert.assertStringIncludes(content, "IsSurplus", "Should define IsSurplus column");
    });
    Bdd.it("should use IF function for conditional logic", async () => {
      let content = await Deno.readTextFile("dax/columns.dax");
      Assert.assertStringIncludes(content, "IF", "Should use IF function");
      Assert.assertStringIncludes(content, "NetIncome", "Should reference NetIncome measure");
    });
    Bdd.it("should return boolean values", async () => {
      let content = await Deno.readTextFile("dax/columns.dax");
      Assert.assertStringIncludes(content, "TRUE()", "Should return TRUE() for surplus");
      Assert.assertStringIncludes(content, "FALSE()", "Should return FALSE() for deficit");
    });
  });
});

Bdd.describe("DAX Syntax Validation", () => {
  Bdd.it("should have matching parentheses in measures.dax", async () => {
    let content = await Deno.readTextFile("dax/measures.dax");
    let openParens = countChar(content, "(");
    let closeParens = countChar(content, ")");
    Assert.assertEquals(openParens, closeParens, "Parentheses should be balanced");
  });
  Bdd.it("should have matching parentheses in columns.dax", async () => {
    let content = await Deno.readTextFile("dax/columns.dax");
    let openParens = countChar(content, "(");
    let closeParens = countChar(content, ")");
    Assert.assertEquals(openParens, closeParens, "Parentheses should be balanced");
  });
  Bdd.it("should have matching brackets in measures.dax", async () => {
    let content = await Deno.readTextFile("dax/measures.dax");
    let openBrackets = countChar(content, "[");
    let closeBrackets = countChar(content, "]");
    Assert.assertEquals(openBrackets, closeBrackets, "Brackets should be balanced");
  });
  Bdd.it("should have matching quotes in measures.dax", async () => {
    let content = await Deno.readTextFile("dax/measures.dax");
    let singleQuotes = countChar(content, "'");
    Assert.assertEquals(singleQuotes % 2, 0, "Single quotes should be balanced");
  });
});

export {
  countChar,
}
/*  Not a pure module */
