// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mod from "../../src/Mod.res.js";
import * as Assert from "../../src/bindings/Assert.res.js";
import * as Buntest from "bun:test";

Buntest.describe("Module Exports", () => {
  Buntest.it("should export VERSION constant", () => {
    Assert.assertExists(Mod.version, "VERSION should be exported");
    Assert.assertEquals(Mod.version, "0.1.0", "VERSION should be 0.1.0");
  });
  Buntest.it("should export PROJECT_NAME constant", () => {
    Assert.assertExists(Mod.projectName, "PROJECT_NAME should be exported");
    Assert.assertEquals(Mod.projectName, "SuperNorma", "PROJECT_NAME should be SuperNorma");
  });
});

Buntest.describe("Financial Calculations", () => {
  Buntest.describe("calculateNetIncome", () => {
    Buntest.it("should calculate positive net income", () => {
      let result = Mod.calculateNetIncome({
        income: 5000.0,
        expenses: 3000.0,
        savings: 2000.0
      });
      Assert.assertEquals(result, 2000.0, "Net income should be 2000");
    });
    Buntest.it("should calculate negative net income", () => {
      let result = Mod.calculateNetIncome({
        income: 3000.0,
        expenses: 4000.0,
        savings: 0.0
      });
      Assert.assertEquals(result, -1000.0, "Net income should be -1000");
    });
    Buntest.it("should calculate zero net income", () => {
      let result = Mod.calculateNetIncome({
        income: 3000.0,
        expenses: 3000.0,
        savings: 0.0
      });
      Assert.assertEquals(result, 0.0, "Net income should be 0");
    });
  });
  Buntest.describe("isSurplus", () => {
    Buntest.it("should return true for surplus", () => Assert.assertEquals(Mod.isSurplus({
      income: 5000.0,
      expenses: 3000.0,
      savings: 2000.0
    }), true, "Should be a surplus"));
    Buntest.it("should return false for deficit", () => Assert.assertEquals(Mod.isSurplus({
      income: 3000.0,
      expenses: 4000.0,
      savings: 0.0
    }), false, "Should be a deficit"));
    Buntest.it("should return false for break-even", () => Assert.assertEquals(Mod.isSurplus({
      income: 3000.0,
      expenses: 3000.0,
      savings: 0.0
    }), false, "Break-even should not be surplus"));
  });
  Buntest.describe("calculateTotalSavings", () => {
    Buntest.it("should sum savings from multiple records", () => {
      let records = [
        {
          income: 4000.0,
          expenses: 2500.0,
          savings: 1500.0
        },
        {
          income: 3500.0,
          expenses: 2000.0,
          savings: 1500.0
        },
        {
          income: 5000.0,
          expenses: 3000.0,
          savings: 2000.0
        }
      ];
      let result = Mod.calculateTotalSavings(records);
      Assert.assertEquals(result, 5000.0, "Total savings should be 5000");
    });
    Buntest.it("should return 0 for empty array", () => {
      let result = Mod.calculateTotalSavings([]);
      Assert.assertEquals(result, 0.0, "Empty array should return 0");
    });
    Buntest.it("should handle single record", () => {
      let records = [{
          income: 4000.0,
          expenses: 2500.0,
          savings: 1500.0
        }];
      let result = Mod.calculateTotalSavings(records);
      Assert.assertEquals(result, 1500.0, "Single record savings should be 1500");
    });
  });
});

Buntest.describe("Pension Calculations", () => {
  Buntest.describe("calculatePensionProjection", () => {
    Buntest.it("should project pension growth at default rate", () => {
      let result = Mod.calculatePensionProjection({
        pensionType: "DC",
        amount: 100000.0,
        contributionPercent: 5.0,
        drawdownAge: 65
      }, 55, undefined);
      Assert.assertEquals(result > 160000.0, true, "Projection should show growth");
      Assert.assertEquals(result < 165000.0, true, "Projection should be reasonable");
    });
    Buntest.it("should project pension at custom growth rate", () => {
      let result = Mod.calculatePensionProjection({
        pensionType: "DB",
        amount: 200000.0,
        contributionPercent: 6.0,
        drawdownAge: 65
      }, 60, 0.04);
      Assert.assertEquals(result > 240000.0, true, "Projection should show growth");
      Assert.assertEquals(result < 250000.0, true, "Projection should be reasonable");
    });
    Buntest.it("should return current amount if already at retirement age", () => {
      let result = Mod.calculatePensionProjection({
        pensionType: "SIPP",
        amount: 150000.0,
        contributionPercent: 5.0,
        drawdownAge: 65
      }, 65, undefined);
      Assert.assertEquals(result, 150000.0, "Should return current amount at retirement");
    });
    Buntest.it("should return current amount if past retirement age", () => {
      let result = Mod.calculatePensionProjection({
        pensionType: "ISA",
        amount: 50000.0,
        contributionPercent: 5.0,
        drawdownAge: 62
      }, 70, undefined);
      Assert.assertEquals(result, 50000.0, "Should return current amount past retirement");
    });
  });
});

/*  Not a pure module */
