// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Assert from "../../src/bindings/Assert.res.js";
import * as Runtime from "../../src/bindings/Runtime.res.js";
import * as Buntest from "bun:test";

Buntest.describe("UI Module Source", () => {
  Buntest.describe("UI.res source file", () => {
    Buntest.it("should exist and be valid ReScript", async () => {
      let content = await Runtime.readTextFile("src/UI.res");
      Assert.assertExists(content, "UI.res should exist");
      return Assert.assertStringIncludes(content, "let init", "Should define init function");
    });
    Buntest.it("should have DOM bindings", async () => {
      let content = await Runtime.readTextFile("src/UI.res");
      Assert.assertStringIncludes(content, "@val", "Should have @val decorators");
      return Assert.assertStringIncludes(content, "querySelector", "Should bind querySelector");
    });
    Buntest.it("should handle form submission", async () => {
      let content = await Runtime.readTextFile("src/UI.res");
      Assert.assertStringIncludes(content, "onsubmit", "Should handle onsubmit");
      return Assert.assertStringIncludes(content, "alert", "Should use alert for feedback");
    });
    Buntest.it("should use Option for null safety", async () => {
      let content = await Runtime.readTextFile("src/UI.res");
      Assert.assertStringIncludes(content, "Nullable.toOption", "Should convert nullable to Option");
      return Assert.assertStringIncludes(content, "Option.forEach", "Should use Option.forEach");
    });
  });
});

Buntest.describe("UI Module Compiled", () => {
  Buntest.it("should have compiled JavaScript file", async () => {
    let content = await Runtime.readTextFile("src/UI.res.js");
    Assert.assertExists(content, "UI.res.js should exist");
    return Assert.assertStringIncludes(content, "Generated by ReScript", "Should have ReScript comment");
  });
  Buntest.it("should export init function", async () => {
    let content = await Runtime.readTextFile("src/UI.res.js");
    Assert.assertStringIncludes(content, "export", "Should have export");
    return Assert.assertStringIncludes(content, "init", "Should export init");
  });
  Buntest.it("should use ES6 module syntax", async () => {
    let content = await Runtime.readTextFile("src/UI.res.js");
    Assert.assertStringIncludes(content, "import", "Should use import statements");
    return Assert.assertStringIncludes(content, "export", "Should use export statements");
  });
  Buntest.it("should have correct file suffix", () => {
    let parts = "src/UI.res.js".split("/");
    let basename = parts[parts.length - 1 | 0];
    if (basename !== undefined) {
      return Assert.assertEquals(basename, "UI.res.js", "Compiled file should have .res.js suffix");
    } else {
      return Assert.assertExists(undefined, "Path should have basename");
    }
  });
});

/*  Not a pure module */
