// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2025 Jonathan D.A. Jewell
// Unit tests for UI module

import { assertEquals, assertExists, assertStringIncludes } from "@std/assert";
import { describe, it } from "@std/testing/bdd";

describe("UI Module Source", () => {
  describe("UI.res source file", () => {
    it("should exist and be valid ReScript", async () => {
      const content = await Deno.readTextFile("src/UI.res");
      assertExists(content, "UI.res should exist");
      assertStringIncludes(content, "let init", "Should define init function");
    });

    it("should have DOM bindings", async () => {
      const content = await Deno.readTextFile("src/UI.res");
      assertStringIncludes(content, "@val", "Should have @val decorators");
      assertStringIncludes(content, "querySelector", "Should bind querySelector");
    });

    it("should handle form submission", async () => {
      const content = await Deno.readTextFile("src/UI.res");
      assertStringIncludes(content, "onsubmit", "Should handle onsubmit");
      assertStringIncludes(content, "alert", "Should use alert for feedback");
    });

    it("should use Option for null safety", async () => {
      const content = await Deno.readTextFile("src/UI.res");
      assertStringIncludes(content, "Nullable.toOption", "Should convert nullable to Option");
      assertStringIncludes(content, "Option.forEach", "Should use Option.forEach");
    });
  });
});

describe("UI Module Compiled", () => {
  it("should have compiled JavaScript file", async () => {
    const content = await Deno.readTextFile("src/UI.res.js");
    assertExists(content, "UI.res.js should exist");
    assertStringIncludes(content, "Generated by ReScript", "Should have ReScript comment");
  });

  it("should export init function", async () => {
    const content = await Deno.readTextFile("src/UI.res.js");
    assertStringIncludes(content, "export", "Should have export");
    assertStringIncludes(content, "init", "Should export init");
  });

  it("should use ES6 module syntax", async () => {
    const content = await Deno.readTextFile("src/UI.res.js");
    assertStringIncludes(content, "import", "Should use import statements");
    assertStringIncludes(content, "export", "Should use export statements");
  });

  it("should have correct file suffix", async () => {
    // The compiled file should have .res.js suffix per rescript.json config
    const path = await import("@std/path");
    const testPath = "src/UI.res.js";
    const basename = path.basename(testPath);

    assertEquals(basename, "UI.res.js", "Compiled file should have .res.js suffix");
  });
});
