// SPDX-License-Identifier: PMPL-1.0-or-later
// SPDX-FileCopyrightText: 2025 Jonathan D.A. Jewell
// Unit tests for UI module

open Deno_Std_Assert
open Deno_Std_Testing

let () = describe("UI Module Source", () => {
  describe("UI.res source file", () => {
    itAsync("should exist and be valid ReScript", async () => {
      let content = await Deno_Api.readTextFile("src/UI.res")
      assertExists(content, ~msg="UI.res should exist")
      assertStringIncludes(content, "let init", ~msg="Should define init function")
    })

    itAsync("should have DOM bindings", async () => {
      let content = await Deno_Api.readTextFile("src/UI.res")
      assertStringIncludes(content, "@val", ~msg="Should have @val decorators")
      assertStringIncludes(content, "querySelector", ~msg="Should bind querySelector")
    })

    itAsync("should handle form submission", async () => {
      let content = await Deno_Api.readTextFile("src/UI.res")
      assertStringIncludes(content, "onsubmit", ~msg="Should handle onsubmit")
      assertStringIncludes(content, "alert", ~msg="Should use alert for feedback")
    })

    itAsync("should use Option for null safety", async () => {
      let content = await Deno_Api.readTextFile("src/UI.res")
      assertStringIncludes(
        content,
        "Nullable.toOption",
        ~msg="Should convert nullable to Option",
      )
      assertStringIncludes(content, "Option.forEach", ~msg="Should use Option.forEach")
    })
  })
})

let () = describe("UI Module Compiled", () => {
  itAsync("should have compiled JavaScript file", async () => {
    let content = await Deno_Api.readTextFile("src/UI.res.js")
    assertExists(content, ~msg="UI.res.js should exist")
    assertStringIncludes(content, "Generated by ReScript", ~msg="Should have ReScript comment")
  })

  itAsync("should export init function", async () => {
    let content = await Deno_Api.readTextFile("src/UI.res.js")
    assertStringIncludes(content, "export", ~msg="Should have export")
    assertStringIncludes(content, "init", ~msg="Should export init")
  })

  itAsync("should use ES6 module syntax", async () => {
    let content = await Deno_Api.readTextFile("src/UI.res.js")
    assertStringIncludes(content, "import", ~msg="Should use import statements")
    assertStringIncludes(content, "export", ~msg="Should use export statements")
  })

  it("should have correct file suffix", () => {
    let testPath = "src/UI.res.js"
    let parts = testPath->String.split("/")
    let basename = parts[Array.length(parts) - 1]
    switch basename {
    | Some(name) => assertEquals(name, "UI.res.js", ~msg="Compiled file should have .res.js suffix")
    | None => assertExists(None, ~msg="Path should have basename")
    }
  })
})
