# SPDX-License-Identifier: MPL-2.0
name: Semgrep SAST
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  semgrep:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      security-events: write
      contents: read
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run Semgrep
        run: semgrep scan --sarif --output=semgrep.sarif --config=auto .
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v3.28.1
        with:
          sarif_file: semgrep.sarif
        if: always()
